languages:
  oracle-python-sdk:
    properties:
      - originalName: "minInGBs"
        mapping:
          identifier: "min_in_g_bs"
        includes:
          - ShapeMemoryOptions

      - originalName: "maxInGBs"
        mapping:
          identifier: "max_in_g_bs"
        includes:
          - ShapeMemoryOptions

      - originalName: "defaultPerOcpuInGBs"
        mapping:
          identifier: "default_per_ocpu_in_g_bs"
        includes:
          - ShapeMemoryOptions

      - originalName: "allowedValues"
        mapping:
          identifier: "service_allowed_values"
        includes:
          - ShapeNumaNodesPerSocketPlatformOptions
          - ShapeMemoryEncryptionTechnologyOptions
