[tox]
envlist = py36, py37, py38, py39, py310, py311, py312, py313, flake8
skip_missing_interpreters = true

[testenv]
passenv = PYTHON_TESTS_ADMIN_PASS_PHRASE
          OCI_PYSDK*
setenv = PYTEST_DISABLE_PLUGIN_AUTOLOAD=1
deps = -r{toxinidir}/requirements.txt
allowlist_externals = bash
commands =
    bash buildServiceScripts/run_pytests_unset_proxies.sh []

[testenv:flake8]
skip_install = true
deps = flake8>=3.6.0,<6
commands = flake8 src docs tests examples --exclude src/oci/_vendor,docs/conf.py