# modes:
#   improveColonReadability:
#     enabled: true
#   removePrefix:
#     prefixes:
#       - urnIetfParamsScim
#       - UrnIetfParamsScim
#       - urn_ietf_params_scim_
#       - Urn_ietf_params_scim_
languages:
  oracle-python-sdk:
    properties:
      - originalName: "urn:ietf:params:scim:schemas:oracle:idcs:extension:selfChange:User"
        mapping:
          identifier: "urn_ietf_params_scim_schemas_oracle_idcs_extension_self_change_user"

      - originalName: "urn:ietf:params:scim:schemas:oracle:idcs:extension:OCITags"
        mapping:
          identifier: "urn_ietf_params_scim_schemas_oracle_idcs_extension_oci_tags"

      - originalName: "urn:ietf:params:scim:schemas:oracle:idcs:extension:group:Group"
        mapping:
          identifier: "urn_ietf_params_scim_schemas_oracle_idcs_extension_group_group"
      - originalName: "urn:ietf:params:scim:schemas:oracle:idcs:extension:posix:Group"
        mapping:
          identifier: "urn_ietf_params_scim_schemas_oracle_idcs_extension_posix_group"
      - originalName: "urn:ietf:params:scim:schemas:oracle:idcs:extension:requestable:Group"
        mapping:
          identifier: "urn_ietf_params_scim_schemas_oracle_idcs_extension_requestable_group"
      - originalName: "urn:ietf:params:scim:schemas:oracle:idcs:extension:dbcs:Group"
        mapping:
          identifier: "urn_ietf_params_scim_schemas_oracle_idcs_extension_dbcs_group"
      - originalName: "urn:ietf:params:scim:schemas:oracle:idcs:extension:dynamic:Group"
        mapping:
          identifier: "urn_ietf_params_scim_schemas_oracle_idcs_extension_dynamic_group"

      - originalName: "urn:ietf:params:scim:schemas:oracle:idcs:extension:social:IdentityProvider"
        mapping:
          identifier: "urn_ietf_params_scim_schemas_oracle_idcs_extension_social_identity_provider"
      - originalName: "urn:ietf:params:scim:schemas:oracle:idcs:extension:x509:IdentityProvider"
        mapping:
          identifier: "urn_ietf_params_scim_schemas_oracle_idcs_extension_x509_identity_provider"

      - originalName: "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"
        mapping:
          identifier: "urn_ietf_params_scim_schemas_extension_enterprise2_0_user"
      - originalName: "urn:ietf:params:scim:schemas:oracle:idcs:extension:user:User"
        mapping:
          identifier: "urn_ietf_params_scim_schemas_oracle_idcs_extension_user_user"
      - originalName: "urn:ietf:params:scim:schemas:oracle:idcs:extension:passwordState:User"
        mapping:
          identifier: "urn_ietf_params_scim_schemas_oracle_idcs_extension_password_state_user"
      - originalName: "urn:ietf:params:scim:schemas:oracle:idcs:extension:userState:User"
        mapping:
          identifier: "urn_ietf_params_scim_schemas_oracle_idcs_extension_user_state_user"
      - originalName: "urn:ietf:params:scim:schemas:oracle:idcs:extension:me:User"
        mapping:
          identifier: "urn_ietf_params_scim_schemas_oracle_idcs_extension_me_user"
      - originalName: "urn:ietf:params:scim:schemas:oracle:idcs:extension:posix:User"
        mapping:
          identifier: "urn_ietf_params_scim_schemas_oracle_idcs_extension_posix_user"
      - originalName: "urn:ietf:params:scim:schemas:oracle:idcs:extension:mfa:User"
        mapping:
          identifier: "urn_ietf_params_scim_schemas_oracle_idcs_extension_mfa_user"
      - originalName: "urn:ietf:params:scim:schemas:oracle:idcs:extension:securityQuestions:User"
        mapping:
          identifier: "urn_ietf_params_scim_schemas_oracle_idcs_extension_security_questions_user"
      - originalName: "urn:ietf:params:scim:schemas:oracle:idcs:extension:selfRegistration:User"
        mapping:
          identifier: "urn_ietf_params_scim_schemas_oracle_idcs_extension_self_registration_user"
      - originalName: "urn:ietf:params:scim:schemas:oracle:idcs:extension:termsOfUse:User"
        mapping:
          identifier: "urn_ietf_params_scim_schemas_oracle_idcs_extension_terms_of_use_user"
      - originalName: "urn:ietf:params:scim:schemas:oracle:idcs:extension:userCredentials:User"
        mapping:
          identifier: "urn_ietf_params_scim_schemas_oracle_idcs_extension_user_credentials_user"
      - originalName: "urn:ietf:params:scim:schemas:oracle:idcs:extension:capabilities:User"
        mapping:
          identifier: "urn_ietf_params_scim_schemas_oracle_idcs_extension_capabilities_user"
      - originalName: "urn:ietf:params:scim:schemas:oracle:idcs:extension:dbCredentials:User"
        mapping:
          identifier: "urn_ietf_params_scim_schemas_oracle_idcs_extension_db_credentials_user"

      - originalName: "urn:ietf:params:scim:schemas:oracle:idcs:extension:kerberosUser:User"
        mapping:
          identifier: "urn_ietf_params_scim_schemas_oracle_idcs_extension_kerberos_user_user"
      - originalName: "urn:ietf:params:scim:schemas:oracle:idcs:extension:adaptive:User"
        mapping:
          identifier: "urn_ietf_params_scim_schemas_oracle_idcs_extension_adaptive_user"
      - originalName: "urn:ietf:params:scim:schemas:oracle:idcs:extension:sff:User"
        mapping:
          identifier: "urn_ietf_params_scim_schemas_oracle_idcs_extension_sff_user"
      - originalName: "urn:ietf:params:scim:schemas:oracle:idcs:extension:socialAccount:User"
        mapping:
          identifier: "urn_ietf_params_scim_schemas_oracle_idcs_extension_social_account_user"
      - originalName: "urn:ietf:params:scim:schemas:oracle:idcs:extension:dbUser:User"
        mapping:
          identifier: "urn_ietf_params_scim_schemas_oracle_idcs_extension_db_user_user"
      - originalName: "urn:ietf:params:scim:schemas:oracle:idcs:extension:passwordless:User"
        mapping:
          identifier: "urn_ietf_params_scim_schemas_oracle_idcs_extension_passwordless_user"

      # 2023-07-20 additions
      - originalName: "urn:ietf:params:scim:schemas:oracle:idcs:extension:radiusApp:App"
        mapping:
          identifier: "urn_ietf_params_scim_schemas_oracle_idcs_extension_radius_app_app"
      - originalName: "urn:ietf:params:scim:schemas:oracle:idcs:extension:samlServiceProvider_app"
        mapping:
          identifier: "urn_ietf_params_scim_schemas_oracle_idcs_extension_saml_service_provider_app"
      - originalName: "urn:ietf:params:scim:schemas:oracle:idcs:extension:webTierPolicy_app"
        mapping:
          identifier: "urn_ietf_params_scim_schemas_oracle_idcs_extension_web_tier_policy_app"
      - originalName: "urn:ietf:params:scim:schemas:oracle:idcs:extension:managedapp_app"
        mapping:
          identifier: "urn_ietf_params_scim_schemas_oracle_idcs_extension_managedapp_app"
      - originalName: "urn:ietf:params:scim:schemas:oracle:idcs:extension:formFillAppTemplate_app_template"
        mapping:
          identifier: "urn_ietf_params_scim_schemas_oracle_idcs_extension_form_fill_app_template_app_template"
      - originalName: "urn:ietf:params:scim:schemas:oracle:idcs:extension:opcService:App"
        mapping:
          identifier: "urn_ietf_params_scim_schemas_oracle_idcs_extension_opc_service_app"
      - originalName: "urn:ietf:params:scim:schemas:oracle:idcs:extension:kerberosRealm:App"
        mapping:
          identifier: "urn_ietf_params_scim_schemas_oracle_idcs_extension_kerberos_realm_app"
      - originalName: "urn:ietf:params:scim:schemas:oracle:idcs:extension:requestable:App"
        mapping:
          identifier: "urn_ietf_params_scim_schemas_oracle_idcs_extension_requestable_app"
      - originalName: "urn:ietf:params:scim:schemas:oracle:idcs:extension:formFillApp:App"
        mapping:
          identifier: "urn_ietf_params_scim_schemas_oracle_idcs_extension_form_fill_app_app"
      - originalName: "urn:ietf:params:scim:schemas:oracle:idcs:extension:dbcs:App"
        mapping:
          identifier: "urn_ietf_params_scim_schemas_oracle_idcs_extension_dbcs_app"
      - originalName: "urn:ietf:params:scim:schemas:oracle:idcs:extension:enterpriseApp:App"
        mapping:
          identifier: "urn_ietf_params_scim_schemas_oracle_idcs_extension_enterprise_app_app"
      - originalName: "urn:ietf:params:scim:schemas:oracle:idcs:extension:multicloudServiceApp:App"
        mapping:
          identifier: "urn_ietf_params_scim_schemas_oracle_idcs_extension_multicloud_service_app_app"
      - originalName: "urn:ietf:params:scim:schemas:oracle:idcs:extension:thirdParty:AuthenticationFactorSettings"
        mapping:
          identifier: "urn_ietf_params_scim_schemas_oracle_idcs_extension_third_party_authentication_factor_settings"
      - originalName: "urn:ietf:params:scim:schemas:oracle:idcs:extension:fido:AuthenticationFactorSettings"
        mapping:
          identifier: "urn_ietf_params_scim_schemas_oracle_idcs_extension_fido_authentication_factor_settings"