# coding: utf-8
# Copyright (c) 2016, 2026, Oracle and/or its affiliates.  All rights reserved.
# This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.

# NOTE: This class is auto generated by OracleSDKGenerator. DO NOT EDIT. API Version: 20210415


from oci.util import formatted_flat_dict, NONE_SENTINEL, value_allowed_none_or_none_sentinel  # noqa: F401
from oci.decorators import init_model_state_from_kwargs


@init_model_state_from_kwargs
class CreateOciFssExportDetails(object):
    """
    An OCI File Storage Service (FSS) Export. Check https://docs.oracle.com/en-us/iaas/api/#/en/filestorage/20171215/Export/ for more details.
    """

    #: A constant which can be used with the oci_fss_export_type property of a CreateOciFssExportDetails.
    #: This constant has a value of "OCID"
    OCI_FSS_EXPORT_TYPE_OCID = "OCID"

    def __init__(self, **kwargs):
        """
        Initializes a new CreateOciFssExportDetails object with values from keyword arguments. This class has the following subclasses and if you are using this class as input
        to a service operations then you should favor using a subclass over the base class:

        * :class:`~oci.container_instances.models.CreateOciFssExportIdDetails`

        The following keyword arguments are supported (corresponding to the getters/setters of this class):

        :param oci_fss_export_type:
            The value to assign to the oci_fss_export_type property of this CreateOciFssExportDetails.
            Allowed values for this property are: "OCID"
        :type oci_fss_export_type: str

        """
        self.swagger_types = {
            'oci_fss_export_type': 'str'
        }
        self.attribute_map = {
            'oci_fss_export_type': 'ociFssExportType'
        }
        self._oci_fss_export_type = None

    @staticmethod
    def get_subtype(object_dictionary):
        """
        Given the hash representation of a subtype of this class,
        use the info in the hash to return the class of the subtype.
        """
        type = object_dictionary['ociFssExportType']

        if type == 'OCID':
            return 'CreateOciFssExportIdDetails'
        else:
            return 'CreateOciFssExportDetails'

    @property
    def oci_fss_export_type(self):
        """
        Gets the oci_fss_export_type of this CreateOciFssExportDetails.
        Determines the mode for supplying the OCI File Storage Service (FSS) Export details.
        The value must be an OCID unless your tenancy is allowed to use PATH as a value.

        Allowed values for this property are: "OCID"


        :return: The oci_fss_export_type of this CreateOciFssExportDetails.
        :rtype: str
        """
        return self._oci_fss_export_type

    @oci_fss_export_type.setter
    def oci_fss_export_type(self, oci_fss_export_type):
        """
        Sets the oci_fss_export_type of this CreateOciFssExportDetails.
        Determines the mode for supplying the OCI File Storage Service (FSS) Export details.
        The value must be an OCID unless your tenancy is allowed to use PATH as a value.


        :param oci_fss_export_type: The oci_fss_export_type of this CreateOciFssExportDetails.
        :type: str
        """
        allowed_values = ["OCID"]
        if not value_allowed_none_or_none_sentinel(oci_fss_export_type, allowed_values):
            raise ValueError(
                f"Invalid value for `oci_fss_export_type`, must be None or one of {allowed_values}"
            )
        self._oci_fss_export_type = oci_fss_export_type

    def __repr__(self):
        return formatted_flat_dict(self)

    def __eq__(self, other):
        if other is None:
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not self == other
